<script lang="ts">
    import { Button } from "$lib/components/ui/button";
    import * as Accordion from "$lib/components/ui/accordion";
    import { Shield, ArrowLeft } from "lucide-svelte";
</script>

<svelte:head>
    <title>Terms of Service | ContractChecker.net</title>
    <meta name="description" content="ContractChecker.net Terms of Service - Please read carefully before using our service." />
    <link rel="canonical" href="https://www.contractchecker.net/terms" />
</svelte:head>

<div class="min-h-screen bg-slate-50 font-sans">
    <nav class="sticky top-0 z-50 bg-white/80 backdrop-blur-sm border-b border-slate-200">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between items-center h-16">
                <a href="/" class="flex items-center gap-2">
                    <img
                        src="https://storage.contractchecker.net/header.webp"
                        alt="ContractChecker Logo"
                        class="h-10 w-auto"
                    />
                </a>
                <a href="/" class="flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-electric-blue transition-colors">
                    <ArrowLeft class="h-4 w-4" />
                    Back to Home
                </a>
            </div>
        </div>
    </nav>

    <div class="max-w-4xl mx-auto px-4 py-12">
        <div class="bg-white rounded-xl shadow-sm border border-slate-200 p-8 md:p-12">
            <div class="flex items-center gap-3 mb-8">
                <div class="w-12 h-12 rounded-full bg-electric-blue/10 flex items-center justify-center">
                    <Shield class="h-6 w-6 text-electric-blue" />
                </div>
                <div>
                    <h1 class="font-serif text-3xl font-bold text-deep-justice">Terms of Service</h1>
                    <p class="text-sm text-slate-500">Effective Date: February 23, 2026</p>
                </div>
            </div>

            <div class="prose prose-slate max-w-none space-y-8">
                <div class="bg-slate-50 p-4 rounded-lg border border-slate-200 mb-8">
                    <p class="text-sm text-slate-600 font-medium">
                        <strong>IMPORTANT LEGAL NOTICE:</strong> PLEASE READ THESE TERMS CAREFULLY BEFORE USING CONTRACTCHECKER.NET. BY ACCESSING OR USING OUR SERVICE, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO ALL OF THESE TERMS, DO NOT USE THE SERVICE.
                    </p>
                </div>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">1. DEFINITIONS</h2>
                    <p class="text-slate-600 mb-4">For the purposes of these Terms of Service ("<strong>Terms</strong>"):</p>
                    <ul class="list-disc pl-6 space-y-2 text-slate-600">
                        <li>"<strong>Company</strong>", "<strong>We</strong>", "<strong>Us</strong>", or "<strong>Our</strong>" refers to ContractChecker.net, its officers, directors, employees, agents, and affiliates.</li>
                        <li>"<strong>Service</strong>" refers to the ContractChecker.net web application, including all features, AI analysis tools, and report generation functionalities.</li>
                        <li>"<strong>User</strong>", "<strong>You</strong>", or "<strong>Your</strong>" refers to any person who accesses or uses the Service.</li>
                        <li>"<strong>Content</strong>" refers to all text, data, analyses, suggestions, reports, and other materials provided by the Service.</li>
                    </ul>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">2. NATURE OF SERVICE – INFORMATIONAL PURPOSES ONLY</h2>
                    <div class="bg-red-50 p-4 rounded-lg border border-red-200 mb-4">
                        <p class="text-gavel-red font-bold text-sm mb-2">⚠️ CRITICAL DISCLAIMER</p>
                        <p class="text-slate-600 text-sm">
                            THE SERVICE PROVIDES AI-GENERATED SUGGESTIONS, ANALYSIS, REFERENCES, AND INFORMATIONAL CONTENT ONLY. THE SERVICE DOES NOT PROVIDE PROFESSIONAL, LEGAL, FINANCIAL, OR BINDING TRANSACTIONAL ADVICE OF ANY KIND.
                        </p>
                    </div>
                    <p class="text-slate-600 mb-4">
                        ContractChecker.net utilizes artificial intelligence and machine learning models to analyze contract documents and perform entity verification against publicly available databases. All outputs generated by the Service are:
                    </p>
                    <ul class="list-disc pl-6 space-y-2 text-slate-600">
                        <li><strong>Informational only</strong> and shall not be construed as legal advice;</li>
                        <li><strong>Not a substitute</strong> for consultation with a qualified attorney, accountant, or other licensed professional;</li>
                        <li><strong>Subject to limitations</strong> inherent in AI systems, including potential inaccuracies, omissions, and outdated information;</li>
                        <li><strong>Not binding</strong> on any party and do not create an attorney-client relationship;</li>
                        <li><strong>Not guaranteed</strong> to be complete, accurate, or applicable to any specific situation.</li>
                    </ul>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">3. "AS IS" AND DISCLAIMER OF ALL WARRANTIES</h2>
                    <div class="bg-slate-100 p-4 rounded-lg border border-slate-300 mb-4">
                        <p class="text-slate-700 font-bold text-sm uppercase tracking-wide">Express Disclaimer</p>
                    </div>
                    <p class="text-slate-600 mb-4">
                        THE SERVICE IS PROVIDED ON AN "AS-IS" AND "AS-AVAILABLE" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY EXPRESSLY DISCLAIMS ALL EXPRESS, IMPLIED, AND STATUTORY WARRANTIES, INCLUDING BUT NOT LIMITED TO:
                    </p>
                    <ul class="list-disc pl-6 space-y-2 text-slate-600">
                        <li><strong>WARRANTIES OF MERCHANTABILITY</strong> – The Service is provided without warranty of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, or non-infringement;</li>
                        <li><strong>WARRANTIES OF ACCURACY</strong> – We do not guarantee the accuracy, completeness, reliability, or absolute reliability of any suggestions, analyses, reports, or Content provided by the Service;</li>
                        <li><strong>WARRANTIES OF AVAILABILITY</strong> – We do not warrant that the Service will be uninterrupted, secure, error-free, or completely free of viruses or other harmful components;</li>
                        <li><strong>WARRANTIES OF RESULTS</strong> – We do not warrant that the use of the Service will produce any specific results, prevent any fraud, or ensure the validity or enforceability of any contract.</li>
                    </ul>
                    <p class="text-slate-600 mt-4">
                        You acknowledge that any reliance on the Service, its Content, or any analysis generated thereby shall be at Your sole and exclusive risk.
                    </p>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">4. LIMITATION OF LIABILITY – ABSOLUTE RELEASE</h2>
                    <div class="bg-red-50 p-4 rounded-lg border border-red-200 mb-4">
                        <p class="text-gavel-red font-bold text-sm mb-2">⚠️ HOLD HARMLESS AND INDEMNIFICATION</p>
                        <p class="text-slate-600 text-sm">
                            THIS SECTION 4 CONTAINS A BINDING ARBITRATION CLAUSE AND A WAIVER OF YOUR RIGHTS TO A JURY TRIAL. PLEASE READ CAREFULLY.
                        </p>
                    </div>
                    <p class="text-slate-600 mb-4">
                        <strong>4.1 Absolute Limitation of Liability.</strong> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, AFFILIATES, SUCCESSORS, OR ASSIGNS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, PUNITIVE, OR OTHER DAMAGES WHATSOEVER, INCLUDING BUT NOT LIMITED TO:
                    </p>
                    <ul class="list-disc pl-6 space-y-2 text-slate-600">
                        <li>Damages for loss of profits, goodwill, use, data, or other intangible losses;</li>
                        <li>Damages resulting from Your reliance on any Content, suggestions, or analysis provided by the Service;</li>
                        <li>Damages resulting from any decision made, action taken, or transaction entered into based on the Service's outputs;</li>
                        <li>Damages resulting from fraud, scams, misrepresentation, or negligence of third parties detected or not detected by the Service;</li>
                        <li>Damages resulting from unfavorable contract terms, unfavorable transaction outcomes, or loss of business opportunities;</li>
                        <li>Damages resulting from the failure to detect fraudulent entities, shell companies, or imposter businesses;</li>
                        <li>Attorney's fees and costs, regardless of whether a lawsuit is filed;</li>
                        <li>Any damages arising out of or relating to these Terms or Your use of the Service.</li>
                    </ul>
                    <p class="text-slate-600 mt-4 mb-4">
                        <strong>4.2 Assumption of Risk.</strong> You expressly acknowledge and agree that if You act upon the Service's suggestions, analysis, or recommendations and subsequently:
                    </p>
                    <ul class="list-disc pl-6 space-y-2 text-slate-600">
                        <li>Suffer any material or immaterial loss, financial or otherwise;</li>
                        <li>Become a victim of fraud, scams, or deceptive practices;</li>
                        <li>Experience third-party negligence or wrongdoing;</li>
                        <li>Face unfavorable contract terms, transaction outcomes, or legal liability;</li>
                        <li>Enter into unfavorable agreements or transactions;</li>
                    </ul>
                    <p class="text-slate-600 mt-4">
                        THE RISK AND RESPONSIBILITY FOR ALL SUCH OUTCOMES SHALL BE 100% YOURS. THE COMPANY SHALL HAVE NO LIABILITY WHATSOEVER FOR ANY SUCH DAMAGES OR LOSSES.
                    </p>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">5. HOLD HARMLESS AND INDEMNIFICATION</h2>
                    <p class="text-slate-600 mb-4">
                        <strong>5.1 Indemnification.</strong> You agree to indemnify, defend, and hold harmless the Company and its officers, directors, employees, agents, affiliates, successors, and assigns from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorney's fees) arising out of or relating to:
                    </p>
                    <ul class="list-disc pl-6 space-y-2 text-slate-600">
                        <li>Your use of or reliance upon the Service or any Content provided thereby;</li>
                        <li>Your violation of these Terms or any applicable law or regulation;</li>
                        <li>Your decision to enter into any contract, transaction, or agreement based on the Service's outputs;</li>
                        <li>Any claim by a third party that Your use of the Service caused or contributed to any damage or loss suffered by such third party;</li>
                        <li>Any actual or alleged fraud, misrepresentation, or illegal conduct by You or related to Your use of the Service.</li>
                    </ul>
                    <p class="text-slate-600 mt-4 mb-4">
                        <strong>5.2 Release.</strong> You hereby release the Company and its officers, directors, employees, agents, affiliates, successors, and assigns from any and all claims, demands, damages, actions, causes of action, or suits of any kind or nature whatsoever, whether known or unknown, arising out of or relating to Your use of the Service or any Content provided thereby.
                    </p>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">6. NOT PROFESSIONAL SERVICES</h2>
                    <div class="bg-amber-50 p-4 rounded-lg border border-amber-200 mb-4">
                        <p class="text-amber-800 font-bold text-sm mb-2">⚠️ NOT A LAW FIRM OR FINANCIAL ADVISOR</p>
                        <p class="text-slate-600 text-sm">
                            ContractChecker.net is not a law firm, not a lawyer, not a bar association, not a legal referral service, not a financial advisor, and not a broker-dealer. No attorney-client relationship is created by Your use of the Service.
                        </p>
                    </div>
                    <p class="text-slate-600">
                        Nothing in the Service constitutes legal advice, financial advice, investment advice, or any other form of professional advice. You should seek the advice of qualified professionals before making any legal, financial, or business decisions. The Service's analysis and suggestions are not a substitute for professional judgment.
                    </p>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">7. USER REPRESENTATIONS AND ACKNOWLEDGMENTS</h2>
                    <p class="text-slate-600 mb-4">By using the Service, You represent and warrant that:</p>
                    <ul class="list-disc pl-6 space-y-2 text-slate-600">
                        <li>You have read, understood, and agree to be bound by these Terms;</li>
                        <li>You have the legal capacity and authority to enter into these Terms;</li>
                        <li>You understand that the Service is provided for informational purposes only;</li>
                        <li>You understand that the Company does not provide legal, financial, or professional advice;</li>
                        <li>You acknowledge that AI systems have inherent limitations and may produce inaccurate or incomplete results;</li>
                        <li>You agree to use the Service at Your own risk and to conduct Your own due diligence;</li>
                        <li>You will not rely solely on the Service's outputs for any significant legal, financial, or business decisions without independent verification.</li>
                    </ul>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">8. INTELLECTUAL PROPERTY</h2>
                    <p class="text-slate-600 mb-4">
                        The Service, including all Content, designs, algorithms, and intellectual property related thereto, is and shall remain the exclusive property of the Company and its licensors. You acknowledge that You have no right, title, or interest in or to any such intellectual property.
                    </p>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">9. GOVERNING LAW AND DISPUTE RESOLUTION</h2>
                    <p class="text-slate-600 mb-4">
                        <strong>9.1 Governing Law.</strong> These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, United States, without regard to its conflict of laws principles.
                    </p>
                    <p class="text-slate-600 mb-4">
                        <strong>9.2 Arbitration.</strong> Any dispute, controversy, or claim arising out of or relating to these Terms or the Service shall be settled by binding arbitration in accordance with the rules of the American Arbitration Association. The arbitration shall be conducted in Wilmington, Delaware, and the decision of the arbitrator shall be final and binding upon both parties.
                    </p>
                    <p class="text-slate-600">
                        <strong>9.3 Waiver of Jury Trial.</strong> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU HEREBY WAIVE YOUR RIGHT TO A TRIAL BY JURY IN ANY ACTION OR PROCEEDING ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE.
                    </p>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">10. MODIFICATIONS TO TERMS</h2>
                    <p class="text-slate-600">
                        The Company reserves the right to modify, amend, or replace these Terms at any time, in its sole discretion. Your continued use of the Service following any such modification constitutes Your acceptance of the modified Terms. It is Your responsibility to review these Terms periodically.
                    </p>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">11. SEVERABILITY</h2>
                    <p class="text-slate-600">
                        If any provision of these Terms is held to be invalid, illegal, or unenforceable, the remaining provisions shall continue in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable while preserving the original intent of the parties.
                    </p>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">12. ENTIRE AGREEMENT</h2>
                    <p class="text-slate-600">
                        These Terms constitute the entire agreement between You and the Company regarding Your use of the Service and supersede all prior or contemporaneous agreements, representations, warranties, and understandings, whether oral or written.
                    </p>
                </section>

                <section>
                    <h2 class="font-serif text-xl font-bold text-deep-justice mb-4">13. CONTACT INFORMATION</h2>
                    <p class="text-slate-600">
                        If You have any questions about these Terms, please contact us at: <a href="mailto:support@contractchecker.net" class="text-electric-blue hover:underline">support@contractchecker.net</a>
                    </p>
                </section>
            </div>

            <div class="mt-12 pt-8 border-t border-slate-200">
                <a href="/" class="inline-flex items-center gap-2 text-electric-blue font-medium hover:underline">
                    <ArrowLeft class="h-4 w-4" />
                    Back to ContractChecker.net
                </a>
            </div>
        </div>
    </div>

    <footer class="bg-slate-900 py-8 px-4 border-t border-slate-800 mt-12">
        <div class="max-w-7xl mx-auto">
            <div class="flex flex-col md:flex-row justify-between items-center gap-4">
                <div class="flex items-center gap-2">
                    <img
                        src="https://storage.contractchecker.net/header.webp"
                        alt="ContractChecker Logo"
                        class="h-6 w-auto opacity-90"
                    />
                </div>
                <p class="text-slate-500 text-sm">
                    &copy; 2026 ContractChecker.net. All rights reserved.
                </p>
                <div class="flex gap-6 text-sm">
                    <a href="/terms" class="text-slate-400 hover:text-white transition-colors">Terms</a>
                    <a href="/privacy" class="text-slate-400 hover:text-white transition-colors">Privacy</a>
                    <a href="mailto:support@contractchecker.net" class="text-slate-400 hover:text-white transition-colors">Contact</a>
                </div>
            </div>
        </div>
    </footer>
</div>

<style>
    .text-electric-blue { color: #2563eb; }
    .bg-electric-blue { background-color: #2563eb; }
    .text-deep-justice { color: #0f172a; }
    .bg-deep-justice { background-color: #0f172a; }
    .text-gavel-red { color: #DC2626; }
    .bg-gavel-red { background-color: #DC2626; }
</style>
